Aliya branch
it-muslim/discord-bots pull request #1
Opened 2018-12-22 07:01 UTC by makysheva

1. бот не реагирует на подобные сообщения: "!thanksWeather" 
2. Попробовала сделать так, чтобы бот на упоминания юзера реагировал, но кажется я что то не то делаю,потому что он и на сообщение без упоминания юзера реагирует.

2018-12-22 07:24 UTC, al-muammar requested changes
Not bad for the first diff. Keep writing code and you will learn how to do it very soon :)

2018-12-22 07:24 UTC, al-muammar commented on auth.json
> +    "token": "NTIzOTI4NDc4MzQxNjYwNzAy.DvgvCw.lsgXCe1q0wD8SWxPEmDoPDrPxew"
Delete this token please. The security of our server because of it is in danger.
Please, add `auth.json` in .gitignore in order not to commit in the future.

2018-12-22 07:24 UTC, al-muammar commented on bot.js
> +//Configure logger settings
Nit: put an empty line after imports in order to logically separate them.

2018-12-22 07:24 UTC, al-muammar commented on bot.js
> +//Initialize Discord Bot
Put an empty string after logger creation in order to separate it from bot creation logic.

2018-12-22 07:24 UTC, al-muammar commented on bot.js
> +    if (regexp.test(message) && channelID == 525249065039036426 && user !== String) {
Let's put `channelID == 525249065039036426` into a separate `if` in the beginning. It will improve:
1. Readability
2. Speed

In your current code, every time you receive a message, you will try to parse it first (which might be quite expensive) and only then check the channelID.

2018-12-22 07:24 UTC, al-muammar commented on bot.js
> +    if (regexp.test(message) && channelID == 525249065039036426 && user !== String) {
`user !== String` is always true. What do you want to check?
User is the name of the user, who sent a message.

2018-12-22 07:34 UTC, makysheva commented on bot.js
> +    if (regexp.test(message) && channelID == 525249065039036426 && user !== String) {
я посмотрела в консоли,  тип user был string, хотела написать кодом следующее: "если user в сообщении НЕ упомянут, то вывести сообщение, что никто не упомянут. "

пыталась и просто в условии if писать просто "user" , но это не дало результата. , написав просто user в условии хотела следующее осуществить: "если есть user в сообщении, т.е. если упомянут user, то выведи сообщение"

 вообще правильно ли я мыслю, используя тип параметра (user)?

2018-12-22 08:59 UTC, makysheva commented on bot.js
> +    if (regexp.test(message) && channelID == 525249065039036426 && user !== String) {
а как мне получить имя пользователя, которого упомянули?

2018-12-22 13:06 UTC, al-muammar requested changes
Now better, but don't fall into extremes :)

2018-12-22 13:06 UTC, al-muammar commented on .gitignore
> +README.md
Wow-wow, easier! We need `README.md` :)
Don't put it in .gitignore.

2018-12-22 13:06 UTC, al-muammar commented on bot.js
> +var Discord = require('discord.io');
From one extreme to another :)
Use empty lines for separating **logical** parts. Let's say, all imports.
```js
// This is the first logical part: imports
var Discord = require('discord.io');
var logger = require('winston');
var  auth = require('./auth.json');

// This is the new logical part, that's why you put an empty line
var auth = require('./auth.json');
var logger = require('winston');
// e.t.c ...
```

2018-12-22 13:06 UTC, al-muammar commented on bot.js
> +var  auth = require('./auth.json');
Do you use auto-formatter?
Please, use it before uploading any diff. There is an extension for sublime, please, use it.

2018-12-22 13:06 UTC, Jihadik commented on bot.js
> +    if(channelID == 525249065039036426) {
1. Formatting
2. Can you avoid nested `if`s? How else could you do it?

2018-12-22 13:11 UTC, Jihadik commented on bot.js
> +    if (regexp.test(message) && channelID == 525249065039036426 && user !== String) {
Try to log `evt`. There is a field `mentions`, i.e. all members that were mentioned in this message. You should use it.

2018-12-22 16:27 UTC, al-muammar requested changes
Keep going!

2018-12-22 16:27 UTC, al-muammar commented on auth.json
> +    "token": "NTIzOTI4NDc4MzQxNjYwNzAy.Dv9-uQ.ymkvoAS7g-XfoxvWGmGm60p0No8"
Remove it. Never ever upload any tokens in GitHub. Before committing anything, use `git diff` to check that you haven't committed anything wrong.

2018-12-22 16:27 UTC, al-muammar commented on .gitignore
> +README.md
Remove `README.md` and add `auth.json` instead.

2018-12-26 10:01 UTC, rguliev requested changes

2018-12-26 10:01 UTC, rguliev commented on bot.js
> +var num_Channel = "525249065039036426";
Do not mix `camelCase` with `underscore_case`. Just rename the variable to `numChannel`. Actually, the comment and the variable name are not descriptive. Means it is difficult to get the meaning of the constant value without reading the whole code. I think it is better to call it something like `ALLOWED_CHANNEL_ID`. Take a look at the Muammar's [bot.js](https://github.com/it-muslim/discord-bots/blob/master/butler-bot/bot.js)
P.S. Uppercase with underscores is usually used for global constants.

2018-12-27 12:56 UTC, al-muammar requested changes
Formatting, formatting, formatting, otherwise, looks very nice!
Please, merge the latest master.

2018-12-27 12:56 UTC, Jihadik commented on bot.js
> +//Канал, в котором бот может реагировать на сообщения
```suggestion
// Канал, в котором бот может реагировать на сообщения
```
Put a space after `//`.

2018-12-27 12:56 UTC, Jihadik commented on bot.js
> +    if(channelID !== ALLOWED_CHANNEL_ID) {
```suggestion
    if (channelID !== ALLOWED_CHANNEL_ID) {
```
1. Formatting
2. Let's move it before `regexp`

2018-12-27 12:56 UTC, Jihadik commented on bot.js
> +    var authorID = evt.d.author.id;
It is the same as `userID`.

2018-12-27 12:56 UTC, Jihadik commented on bot.js
> +    if(!!mentionedUsersID.indexOf(authorID)){
```suggestion
    if (mentionedUsersID.indexOf(authorID)) {
```
This is the same.

2018-12-27 12:56 UTC, Jihadik commented on bot.js
> +    var mentionedUsersID = evt.d.mentions.map(function(item, i, mentions) {
Check here that a user didn't thank himself, write "Don't thank yourself" message and `return`.

2018-12-28 06:48 UTC, makysheva commented on bot.js
> +    var authorID = evt.d.author.id;
когда  пишу ` evt.d.mentions[i].username;`, то выходит  само имя пользователя, а если пишу  `evt.d.mentions[i].id;` , то выходят цифры ` id` пользователя. поэтому отдельно сделала переменную, чтобы использовать имя пользователя в ответном сообщении бота.

2018-12-28 06:49 UTC, makysheva commented on bot.js
> +    if(!!mentionedUsersID.indexOf(authorID)){
да, просто брат Мухаммад сказал привести к логическому преобразованию

2019-01-03 01:28 UTC, closed without merging