Перебор массива обьектов
it-muslim/discord-bots pull request #2
Opened 2018-12-23 18:15 UTC by safbek

Пытаюсь перебрать массив mentions и выводить в message

2018-12-23 19:14 UTC, rguliev requested changes
Забыли упомянуть в описании, что удалили auth.json. Было бы лучше сделать это отдельным pull request'ом.
Есть небольшие замечания по форматированию кода. Если в кратце: убирайте ненужные пустые строки и комментраии.
Отправка сообщения в таком виде нормально работать не будет. Это стоит обсудить отдельно.

2018-12-23 19:14 UTC, rguliev commented on bot.js
> +});*/
Уберите этот большой комментарий. Ниже Вы используете почти тот же самый код. Разницу все равно всегда можно будет посмотреть через git.

2018-12-23 19:14 UTC, rguliev commented on bot.js
> +
Лишняя пустая линия. Можно убрать.

2018-12-23 19:14 UTC, rguliev commented on bot.js
> +let regexp = /\!thanks/gmi;
У Вас в этой части явно что-то не так с форматированием. Я имею в виду отступы.

2018-12-23 19:14 UTC, rguliev commented on bot.js
> +
Много лишних пустых линий. Уберите, пожалуйста.

2018-12-23 19:14 UTC, rguliev commented on bot.js
> +        message: mentions.forEach(function(item, i, mentions) {
Вы где-то рядом. В том смысле, что forEach понадобится. Тут нужно более подробное обсуждение.

2018-12-24 09:47 UTC, rguliev requested changes

2018-12-24 09:47 UTC, rguliev commented on bot.js
> +        message: mentions.forEach(function(item, i, mentions) {
Кстати, кажется, Вы забыли определить mentions.

2018-12-24 09:47 UTC, rguliev commented on bot.js
> +        message: mentions.forEach(function(item, i, mentions) {
Синтаксис метода forEach: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2018-12-24 10:50 UTC, rguliev requested changes
Уже лучше!
Используйте 4 пробела вместо 8. И надо еще немного поработать с обработкой массивов)

2018-12-24 10:50 UTC, rguliev commented on bot.js
> +	let arrUsernames = [];
Лучше переименовать на что-то более явное вроде arrMentionedUsernames.

2018-12-24 10:50 UTC, rguliev commented on bot.js
> +	evt.d.mentions.forEach(function(item, i) {
Зачем тут i? Удалите, если не используете его.

2018-12-24 10:50 UTC, rguliev commented on bot.js
> +			message: evt.d.author.username+ " поблагодарил(a) кого-то вроде (Safiya's bot)" +arrUsernames
1) Эта строчка очень длинная. Разбейте её, пожалуйста, на несколько.
2) `(Safiya's bot)` лучше добавлять в конце строки. А то получается, что поблагодарил кото-то вроде Safiya's bot. То есть как будто сам себя похвалил)
3) Даже если это работает, тут есть проблемка. Вы в строчку передаете массив. " поблагодарил(a) кого-то вроде (Safiya's bot)" +arrUsernames. Нужно массив предварительно в строку тоже превратить. Для этого используйте join: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join

2018-12-24 10:50 UTC, rguliev commented on bot.js
> +
Тоже лишняя пустая строчка:)

2018-12-24 19:05 UTC, al-muammar requested changes
Very strong, to be honest! Few small corrections and you are done!

2018-12-24 19:05 UTC, al-muammar commented on bot.js
> +})
The indent here is wrong.

2018-12-24 19:05 UTC, al-muammar commented on bot.js
>  bot.on('message', function (user, userID, channelID, message, evt) {
Let's add a check in the beginning of this function, that if a userID is the bot user id, then don't go forward and exit the function.

2018-12-24 19:05 UTC, Jihadik commented on bot.js
> +  let regexp = /\!thanks/gmi;
This regexp is good, but still you have a number of corner cases:
1. What if someone wrote `!thankswhatever`, your bot will catch it, but it shouldn't.
2. What if someone wrote `... end of the sentence!thanks Mike for ...`. Your bot will also catch it, but again, I don't think we want it.

2018-12-24 19:05 UTC, Jihadik commented on bot.js
> +  let arrMentionedUsers = [];
```suggestion
   let mentionedUsers = [];
```
Let's remove unnecessary parts from the name of the variable.

2018-12-24 19:05 UTC, Jihadik commented on bot.js
> +      to: channelID,
Maybe we should send all thanks to a specific #thanks channel?

2018-12-24 19:05 UTC, Jihadik commented on bot.js
> +      message: evt.d.author.username+ " поблагодарил(a) пользователя(ей) "
Use formatter here, please.

2018-12-26 13:08 UTC, al-muammar requested changes
Two moments:
1. Fix the formatting, otherwise it's hard to follow what's happening in the code
2. Merge the master
3. Address all Rustam's and my comments

2018-12-26 13:08 UTC, Jihadik commented on bot.js
> +/**/
What is the purpose of this line?

2018-12-26 13:08 UTC, Jihadik commented on bot.js
> +});
Why can't you add here
```js
mentionedUserNames.push(item.username);
```
?

2018-12-29 08:29 UTC, al-muammar requested changes
Very good. You will be done very soon!

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    // Conditions for exiting a function
The function is known, so you have to use a definitive article.
```suggestion
    // Conditions for exiting the function
```

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    const bot_user_id = '523928478341660702';
It's better to use `bot.id`, it is more universal. Remove this line and wherever you used `bot_user_id`, change it by `bot.id`.

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    const allowed_channel = '525249065039036426';
Move it outside the function as I made in `butler-bot`. Additionally, make it uppercase.

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    const authorId = evt.d.author.id;
I think it is equal to `userID`, let's use it?

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    const authorName = evt.d.author.username;
Isn't it the same as `user`? Can't we use `user` instead?

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    if(channelID !== allowed_channel ||
Formatting
```suggestion
    if (channelID !== allowed_channel ||
```

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +        authorId === bot_user_id || !regexp.test(message)){
Formatting
```suggestion
        authorId === bot_user_id || !regexp.test(message)) {
```

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    // Collecting user id
Be consistent
```suggestion
    // Collecting user ids
```

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    if(mentionedUserId.length === 0){
Formatting
```suggestion
    if (mentionedUserId.length === 0) {
```

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    if (!!mentionedUserId.indexOf(authorId)) {
`!!` doesn't have any sense. Additionally, use `contains` instead of `indexOf`.
```suggestion
    if (mentionedUserId.indexOf(authorId)) {
```

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +
Remove this empty line.

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    }else{
Formatting
```suggestion
    } else {
```

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +            message: "Пардон, но всему свое время и место"
The message is not informative, user should understand why his `!thanks` was ignored.

2018-12-29 08:29 UTC, al-muammar commented on thanks-bot/bot.js
> +
Remove this empty line.

2018-12-30 21:23 UTC, al-muammar reviewed
Few small comments, otherwise looks great!

2018-12-30 21:23 UTC, al-muammar commented on .gitignore
> +
Remove this empty line.

2018-12-30 21:23 UTC, al-muammar commented on thanks-bot/bot.js
> +const ALLOWED_CHANNELS = '525249065039036426';
```suggestion
const ALLOWED_CHANNEL_ID = '525249065039036426';
```

2018-12-30 21:23 UTC, al-muammar commented on thanks-bot/bot.js
> +const REGEXP = /\!thanks\b/gmi;
Be more specific:
```suggestion
const THANKS_MESSAGE_REGEXP = /\!thanks\b/gmi;
```

2018-12-31 16:29 UTC, al-muammar requested changes
Cool, you are almost done!
Address all comments and remove package-lock.json

Make sure that `TravisCI` is happy.

2018-12-31 16:29 UTC, al-muammar commented on thanks-bot/bot.js
> +  const THANKS_MESSAGE_REGEXP = /\!thanks\b/gmi
Usually, only global constants are uppercase.
```suggestion
  const thanksMessageRegexp = /!thanks\b/gmi
```
I also deleted `\`, because it turned out that it was unnecessary.

2018-12-31 16:29 UTC, al-muammar commented on thanks-bot/bot.js
> +    userID === BOT_ID || !THANKS_MESSAGE_REGEXP.test(message)) {
Let's use `bot.id` instead.
```suggestion
    userID === bot.id || !THANKS_MESSAGE_REGEXP.test(message)) {
```

2018-12-31 16:29 UTC, al-muammar commented on thanks-bot/bot.js
> +  let mentionedUserId = evt.d.mentions.map(item => item.id)
It should be plural
```suggestion
  let mentionedUserIds = evt.d.mentions.map(item => item.id)
```

2019-01-03 09:06 UTC, al-muammar requested changes
You are almost there!!!

2019-01-03 09:06 UTC, Jihadik commented on thanks-bot/bot.js
> +  let thanks_message_regexp = /!thanks\b/gmi
```suggestion
  let thanksMessageRegexp = /!thanks\b/gmi
```

2019-01-03 09:06 UTC, Jihadik commented on thanks-bot/bot.js
> +  let mentionedUserIds = evt.d.mentions.map(item => item.id)
Let's be consistent.
```suggestion
  let mentionedUserIDs = evt.d.mentions.map(item => item.id)
```

2019-01-03 09:06 UTC, Jihadik commented on thanks-bot/bot.js
> +  let mentionedUserNames = evt.d.mentions.map(item => item.username)
It is used only in line 51, move it inside the `if` at line 47.

2019-01-03 09:06 UTC, Jihadik commented on thanks-bot/bot.js
> +      mentionedUserNames.join(', ') + ' (Safiya\'s bot)'
It's time to remove it :)
```suggestion
      mentionedUserNames.join(', ')
```

2019-01-03 09:06 UTC, Jihadik commented on thanks-bot/bot.js
> +      message: user + ' поблагодарил(a) пользователя(ей) ' +
```suggestion
      message: `${user} поблагодарил(a) пользователя(ей) ` +
```

2019-01-03 09:06 UTC, Jihadik commented on thanks-bot/bot.js
> +  if (!mentionedUserIds.includes(userID)) {
If a user mentioned himself in a thanks message, let's just remove him, instead of writing an error message?

2019-01-04 14:24 UTC, al-muammar approved these changes
Awesome, accepting the PR, looks great.
Can you update the name and the description of the PR?

2019-01-05 16:02 UTC, merged