удалила старую ветку, создала новую
it-muslim/discord-bots pull request #8
Opened 2019-01-03 02:07 UTC by makysheva

2019-01-03 08:59 UTC, al-muammar requested changes
1. Address the comments
2. Make TravisCI happy
3. Rename you PR and add a description

2019-01-03 08:59 UTC, al-muammar commented on .gitignore
> +#folders
delete

2019-01-03 08:59 UTC, al-muammar commented on .gitignore
> +butler-bot/
O_O, delete, please!

2019-01-03 08:59 UTC, al-muammar commented on .gitignore
> +
Delete this empty line.

2019-01-03 08:59 UTC, al-muammar commented on .gitignore
> +#files
Delete it.

2019-01-03 08:59 UTC, Jihadik commented on thanks-bot/bot.js
> +  var regexp = /\!thanks\b/gmi;
Move this expression right before `if (!regexp.test(message))`. Additionally, you don't need the `\`
```suggestion
  var regexp = /!thanks\b/gmi;
```

2019-01-03 08:59 UTC, Jihadik commented on thanks-bot/bot.js
> +  var mentionedUsersID = evt.d.mentions.map(function(item, i, mentions) {
You don't use neither `item` nor `mentions`.
```suggestion
  var mentionedUserIDs = evt.d.mentions.map(function(item, i, mentions) {
```

2019-01-03 08:59 UTC, Jihadik commented on thanks-bot/bot.js
> +  if (mentionedUsersID.includes(authorID)){
Can you move this check right after you collected `mentionedUserIDs`?

2019-01-03 08:59 UTC, Jihadik commented on thanks-bot/bot.js
> +  if (mentionedUsers.length === 0) {
Move it right after `mentionedUserIDs`

2019-01-03 08:59 UTC, Jihadik commented on thanks-bot/bot.js
> +  var authorID = evt.d.author.id;
It is the same as `userID`, you don't need a separate variable.

2019-01-04 00:57 UTC, makysheva commented on thanks-bot/bot.js
> +  var mentionedUsersID = evt.d.mentions.map(function(item, i, mentions) {
в общем когда я убираю `item` и  `mentions`, то он выдает ошибку, что не может найти `id ` 
 и `username` соответственно.

2019-01-29 12:12 UTC, closed without merging